declare @Id int
INSERT INTO [dbo].[Clients]
           ([Enabled]
           ,[ClientId]
           ,[ProtocolType]
           ,[RequireClientSecret]
           ,[ClientName]
           ,[Description]
           ,[ClientUri]
           ,[LogoUri]
           ,[RequireConsent]
           ,[AllowRememberConsent]
           ,[AlwaysIncludeUserClaimsInIdToken]
           ,[RequirePkce]
           ,[AllowPlainTextPkce]
           ,[AllowAccessTokensViaBrowser]
           ,[FrontChannelLogoutUri]
           ,[FrontChannelLogoutSessionRequired]
           ,[BackChannelLogoutUri]
           ,[BackChannelLogoutSessionRequired]
           ,[AllowOfflineAccess]
           ,[IdentityTokenLifetime]
           ,[AccessTokenLifetime]
           ,[AuthorizationCodeLifetime]
           ,[ConsentLifetime]
           ,[AbsoluteRefreshTokenLifetime]
           ,[SlidingRefreshTokenLifetime]
           ,[RefreshTokenUsage]
           ,[UpdateAccessTokenClaimsOnRefresh]
           ,[RefreshTokenExpiration]
           ,[AccessTokenType]
           ,[EnableLocalLogin]
           ,[IncludeJwtId]
           ,[AlwaysSendClientClaims]
           ,[ClientClaimsPrefix]
           ,[PairWiseSubjectSalt]
           ,[Created]
           ,[Updated]
           ,[LastAccessed]
           ,[UserSsoLifetime]
           ,[UserCodeType]
           ,[DeviceCodeLifetime]
           ,[NonEditable])
     VALUES
     (
           1, --[Enabled]
           '58EC0B4B-FCBF-49AF-B1A3-BD8C47D78DB3',--[ClientId]
           'oidc', --[ProtocolType]
           0,--[RequireClientSecret]
           'Service Account', --[ClientName]
           'Service Account', --[Description]
           null, --[ClientUri]
           null, --[LogoUri]
           0, --[RequireConsent]
           1, --[AllowRememberConsent]
           1, --[AlwaysIncludeUserClaimsInIdToken]
           1, --[RequirePkce]
           0,--[AllowPlainTextPkce]
           1, --[AllowAccessTokensViaBrowser]
           null, --[FrontChannelLogoutUri]
           0, --[FrontChannelLogoutSessionRequired]
           null, --[BackChannelLogoutUri]
           0, --[BackChannelLogoutSessionRequired]
           1, --[AllowOfflineAccess]
           3600, --[IdentityTokenLifetime]
           3600, --[AccessTokenLifetime]
           3600, --[AuthorizationCodeLifetime]
           null, --[ConsentLifetime]
           3600, --[AbsoluteRefreshTokenLifetime]
           3600, --[SlidingRefreshTokenLifetime]
           2592000, --[RefreshTokenUsage]
           0, --[UpdateAccessTokenClaimsOnRefresh]
           2592000, --[RefreshTokenExpiration]
           0, --[AccessTokenType]
           1, --[EnableLocalLogin]
           1, --[IncludeJwtId]
           0,--[AlwaysSendClientClaims]
           null, --[ClientClaimsPrefix]
           null, --[PairWiseSubjectSalt]
           getutcdate(),--[Created]
           getutcdate(),--[Updated]
           null, --[LastAccessed]
           null, --[UserSsoLifetime]
           null, --[UserCodeType]
           3600, --[DeviceCodeLifetime]
           1 --[NonEditable]
     )
 SELECT @Id = Scope_Identity()

-- client grant type
INSERT INTO [dbo].[ClientGrantTypes]
           ([GrantType]
           ,[ClientId])
VALUES
('client_credentials', @Id)

INSERT INTO [dbo].[ClientScopes]
           ([Scope]
           ,[ClientId])
VALUES           
('openid', @Id),
('profile', @Id)

INSERT INTO [dbo].[ClientSecrets]
           ([Description]
           ,[Value]
           ,[Expiration]
           ,[Type]
           ,[Created]
           ,[ClientId])
      
VALUES ('SA password', -- [Description]
        'yyKUEXQRRowbCeQ+myk+XdfFzvPjF2aNsVx5y5Zg+zc=',  --[Value]: l2z6YkPkTCW7J5GaR0o7
        null, --[Expiration]
        'SharedSecret', --[Type]
        getutcdate(), --[Created]
        @Id)